export enum CategorieLabels {
  Tickets = "Tickets",
  Food = "Food",
  Caffe = "Caffe",
  Medicine = "Medicine",
  Other = "Other",
  Tax = "Tax",
  Cosmetics = "Cosmetics",
  Documentation = "Documentation",
  Cat = "Cat",
  Cloth = "Cloth",
  Entertainment = "Entertainment",
  Bike = "Bike",
  Home = "Home",
}
export const categorieLabels = [
  CategorieLabels.Food,
  CategorieLabels.Tickets,
  CategorieLabels.Caffe,
  CategorieLabels.Medicine,
  CategorieLabels.Other,
  CategorieLabels.Entertainment,
  CategorieLabels.Bike,
  CategorieLabels.Home,
  CategorieLabels.Tax,
  CategorieLabels.Cosmetics,
  CategorieLabels.Documentation,
  CategorieLabels.Cat,
  CategorieLabels.Cloth,
];
